//! Befehle, die die Web-App aufrufen darf (`plugin:health|…`); daraus
//! entstehen die Rechte `health:allow-…` (permissions/autogenerated).
const COMMANDS: &[&str] = &["status", "request_access", "sessions", "route", "open_settings"];

fn main() {
  tauri_plugin::Builder::new(COMMANDS)
    .android_path("android")
    .build();
}
