//! Befehle, die die Web-App aufrufen darf (`plugin:folder|…`); daraus
//! entstehen die Rechte `folder:allow-…` (permissions/autogenerated).
const COMMANDS: &[&str] = &["pick", "info", "list", "read", "write", "remove", "rename", "reveal", "disconnect", "save", "opened"];

fn main() {
  tauri_plugin::Builder::new(COMMANDS)
    .android_path("android")
    .build();
}
