; Typischer 8-Zoll-Bildschirm (z. B. Golf, Skoda) – 1280 × 720
[general]
touch = true
touchpad = false
controller = false
instrumentcluster = false
resolution = 1280x720
marginheight = 0
marginwidth = 0
dpi = 180
framerate = 30

[sensors]
location = true
night_mode = true
driving_status = true
