; VW ID.3 – breiter, flacher Bildschirm (10 bzw. 12,9 Zoll), sichtbar ~1920 × 720
[general]
touch = true
touchpad = false
controller = false
instrumentcluster = false
resolution = 1920x1080
marginheight = 360
marginwidth = 0
dpi = 200
framerate = 30

[sensors]
location = true
night_mode = true
driving_status = true
