; Älteres Auto / Nachrüstradio 7 Zoll – 800 × 480
[general]
touch = true
touchpad = false
controller = false
instrumentcluster = false
resolution = 800x480
marginheight = 0
marginwidth = 0
dpi = 160
framerate = 30

[sensors]
location = true
night_mode = true
driving_status = true
