; Mercedes MBUX 10,25 Zoll (A-/C-Klasse) – breit, sichtbar ~1920 × 720, dichter
[general]
touch = true
touchpad = false
controller = false
instrumentcluster = false
resolution = 1920x1080
marginheight = 360
marginwidth = 0
dpi = 240
framerate = 30

[sensors]
location = true
night_mode = true
driving_status = true
